import type { Metadata, Viewport } from 'next';
import './globals.css';
import PWARegister from '@/components/PWARegister';
import PreviewOverlay from '@/components/PreviewOverlay';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: '#050510',
};

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_BASE_URL || 'https://ai-game-factory.vercel.app'
  ),
  title: 'AI Game Factory — 바이브 코딩 시뮬레이터 | Preview Build',
  description:
    'AI가 실시간으로 HTML5 게임을 만드는 바이브 코딩 시뮬레이터. 장르·테마·난이도를 선택하면 AI가 즉시 플레이 가능한 게임을 생성합니다.',
  keywords: [
    'AI',
    '바이브 코딩',
    'HTML5 게임',
    '시뮬레이터',
    '게임 팩토리',
    'AI 게임',
    '게임 생성',
    'vibe coding',
  ],
  robots: { index: false, follow: false },
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    apple: [
      { url: '/icons/icon-192.png', sizes: '192x192' },
    ],
  },
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    siteName: 'AI Game Factory',
    title: 'AI Game Factory — 바이브 코딩 시뮬레이터',
    description:
      'AI가 실시간으로 HTML5 게임을 만드는 체험. 장르·테마·난이도를 선택하면 AI가 즉시 게임을 생성합니다.',
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AI Game Factory — 바이브 코딩 시뮬레이터',
    description:
      'AI가 실시간으로 HTML5 게임을 만드는 체험. 장르·테마·난이도를 선택하면 AI가 즉시 게임을 생성합니다.',
    // Twitter shares the OG image generated by app/opengraph-image.tsx
    images: ['/opengraph-image'],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'AI Game Factory',
  },
  other: {
    'apple-mobile-web-app-capable': 'yes',
    'mobile-web-app-capable': 'yes',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body style={{
        margin: 0,
        padding: 0,
        minHeight: '100dvh',
        background: '#050510',
        color: '#e2e8f0',
      }}>
        <PWARegister />
        <PreviewOverlay />
        {children}
      </body>
    </html>
  );
}
